import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fontsource/arimo/400.css";
import "@fontsource/arimo/700.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/700.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { ThemeProvider } from "@mui/material/styles";

import theme from "../theme";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         
         <ThemeProvider theme={theme}>
        <Header/>
        <div className="min-h-screen">
           {children}
        </div>
        <Footer/>
        </ThemeProvider>
      
      </body>
    </html>
  );
}
